baseurl = "http://arianv.com/"
languageCode = "en-us"
title = "Arian's Portfolio"
pygmentsstyle = "monokai"
canonifyurls = true
theme = "secretfolio"
disqusShortname = "arianv"

[Taxonomies]
  series = "series"
  series-desc = "series-desc"
  port_tag = "port_tags"
  tag = "tags"  

[params]
  googleAnalytics = "UA-60507502-1"
